import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import type { IconDefinition } from "@fortawesome/fontawesome-svg-core";
import {
  faBars,
  faBell,
  faMagnifyingGlass,
  faRightFromBracket,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faChevronDown,
  faCalendarDay,
  faCalendarDays,
  faCalendarCheck,
  faCalendarXmark,
  faXmark,
  faTrash,
  faLock,
  faPhone,
  faEnvelope,
  faCheck,
  faCircleCheck,
  faCircleQuestion,
  faDownload,
  faFlask,
  faFileLines,
  faUser,
  faCircleUser,
  faStar,
  faCirclePlus,
  faGavel,
  faFolderOpen,
  faPrescriptionBottleMedical,
  faPills,
  faClock,
  faPersonWalking,
  faTriangleExclamation,
  faCircleHalfStroke,
  faChartLine,
  faChartSimple,
  faCircleXmark,
  faCircleExclamation,
  faCircleInfo,
  faGaugeHigh,
  faBriefcaseMedical,
  faClipboard,
  faSyringe,
  faMoneyBillWave,
  faUserGroup,
  faBullhorn,
  faUserGear,
  faNotesMedical,
  faIdBadge,
  faGear,
  faClockRotateLeft,
  faListCheck,
  faHourglassHalf,
  faReceipt,
  faSignsPost,
  faThermometerHalf,
  faHeartPulse,
  faLungs,
  faGauge,
  faWind,
  faRuler,
  faWeightScale,
  faList,
  faTableList,
  faPrint,
  faCopy,
  faPencil,
  faUpload,
} from "@fortawesome/free-solid-svg-icons";
import { faCircle as faCircleRegular } from "@fortawesome/free-regular-svg-icons";

// Maps the app's original Material-Symbols ligature names (e.g. "check_circle")
// to bundled Font Awesome icons. Swapped in because the Google Fonts-hosted
// Material Symbols font failed to load in network-sandboxed environments,
// silently rendering every icon in the app as raw ligature text (e.g. the
// literal word "warning") instead of a glyph. Font Awesome ships as bundled
// SVG with the app's own JS, so it has no runtime network dependency at all.
const ICON_MAP: Record<string, IconDefinition> = {
  menu: faBars,
  notifications: faBell,
  search: faMagnifyingGlass,
  logout: faRightFromBracket,
  chevron_left: faChevronLeft,
  chevron_right: faChevronRight,
  expand_less: faChevronUp,
  expand_more: faChevronDown,
  calendar_today: faCalendarDay,
  calendar_month: faCalendarDays,
  event_available: faCalendarCheck,
  event_note: faCalendarDay,
  event: faCalendarDay,
  event_busy: faCalendarXmark,
  close: faXmark,
  delete: faTrash,
  lock: faLock,
  call: faPhone,
  mail: faEnvelope,
  check: faCheck,
  check_circle: faCircleCheck,
  help: faCircleQuestion,
  download: faDownload,
  science: faFlask,
  description: faFileLines,
  person: faUser,
  account_circle: faCircleUser,
  star: faStar,
  add_circle: faCirclePlus,
  gavel: faGavel,
  folder_shared: faFolderOpen,
  folder_open: faFolderOpen,
  prescriptions: faPrescriptionBottleMedical,
  medication: faPills,
  schedule: faClock,
  directions_walk: faPersonWalking,
  warning: faTriangleExclamation,
  incomplete_circle: faCircleHalfStroke,
  radio_button_unchecked: faCircleRegular,
  analytics: faChartSimple,
  monitoring: faChartLine,
  cancel: faCircleXmark,
  error: faCircleExclamation,
  info: faCircleInfo,
  dashboard: faGaugeHigh,
  medical_services: faBriefcaseMedical,
  assignment: faClipboard,
  vaccines: faSyringe,
  payments: faMoneyBillWave,
  group: faUserGroup,
  groups: faUserGroup,
  campaign: faBullhorn,
  manage_accounts: faUserGear,
  clinical_notes: faNotesMedical,
  badge: faIdBadge,
  settings: faGear,
  history: faClockRotateLeft,
  pending_actions: faListCheck,
  hourglass_top: faHourglassHalf,
  receipt_long: faReceipt,
  follow_the_signs: faSignsPost,
  thermometer: faThermometerHalf,
  heart_pulse: faHeartPulse,
  lungs: faLungs,
  gauge: faGauge,
  wind: faWind,
  ruler: faRuler,
  weight_scale: faWeightScale,
  view_list: faList,
  table_rows: faTableList,
  print: faPrint,
  copy: faCopy,
  edit: faPencil,
  upload_file: faUpload,
};

export interface IconProps {
  /** Original Material-Symbols ligature name — looked up in ICON_MAP above. */
  name: string;
  className?: string;
}

export function Icon({ name, className }: IconProps) {
  const icon = ICON_MAP[name];
  if (!icon) return null;
  return <FontAwesomeIcon icon={icon} className={className} />;
}
